package:
  name: q2-gunc
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - beautifulsoup4
  - cssutils
  - gunc
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  - q2templates >={{ q2templates }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - parameterized
  - pytest-xdist
  imports:
  - q2_gunc
  - qiime2.plugins.gunc
  commands:
  - pytest --pyargs q2_gunc -n 4
about:
  home: https://github.com/bokulich-lab/q2-gunc
  license: BSD-3-Clause
  license_family: BSD
